Retry setting GitHub status to success before merge
Commit 179b5fb ("Retry merging to master", 2019-09-05) was trying to fix an
issue where `git.finishMerge()` would fail with:
```
+ git push origin @:master
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: 3 of 3 required status checks are expected.
To github.com:<repo>.git
 ! [remote rejected] @ -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:<repo>.git'
```

But looks like the fix didn't work, at least not completely. In this case,
when checking GitHub, the statuses managed by `github.setStatus` were both
in the pending state, even hours after the merge failure. This means that
`github.setStatus` didn't seem to do its job. If there's some intermittent
failure that can cause this, then moving the step into the retry block
should help.